# -*- coding: utf-8 -*-
"""projeto-algoritmo-de-auditoria-de-dados.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NO_oOI4i525gxhL4IxRlynyj5Nzhg522
"""

LIMITE_SEGURANCA = 10

venda1 = float(input("Valor da primeira venda: "))
venda2 = float(input("Valor da segunda venda: "))
venda3 = float(input("Valor da terceira venda: "))

media_final = (venda1 + venda2 + venda3) / 3

def analisar_vendas():

  global LIMITE_SEGURANCA
  LIMITE_SEGURANCA = float(input("Valor liberado pelo gerente: "))


analisar_vendas()

# Saída
print("-"*40)
print(f"Primeira venda: {venda1:.2f} | Tipo: {type(venda1)}")
print(f"Segunda venda: {venda2:.2f} | Tipo: {type(venda2)}")
print(f"Terceira venda: {venda3:.2f} | Tipo: {type(venda3)}")
print(f"Média: {media_final:.2f} | Tipo: {type(media_final)}")
if media_final <= LIMITE_SEGURANCA:
  print("Limite Liberado")
elif media_final > LIMITE_SEGURANCA * 5:
  print("Revisão Manual")
elif media_final > LIMITE_SEGURANCA:
  print("Sistema em Quarentena")
else:
  print("Valor não identificado")
print("-"*40)

analisar_vendas()