# -*- coding: utf-8 -*-
"""desenho-emoji.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PgQrXmxqjUYXh66qyFAwlIFMQ6nV53PB

***Site para estudo: W3School***
"""

# Estruturas de Repetição

for i in range(5): # Começa em zero e vai até 4
 print(i)

# Lista de números
numeros = [1,2,3,4,5]

for numero in numeros:
  print(numero)

# Dicionário
frutas = {"maça": 1, "banana": 2, "laranja": 3}

for fruta in frutas:
  print(fruta + ": " + str(frutas[fruta]))

frutas['banana']

# Tupla de cores
cores = ("vermelho", "verde", "azul")

for cor in cores:
  print(cor)

"""Lista: é uma estrutura de dados ordenada e *mutável*

"""

lista = [5,2,3,4,1]

print("Antes:", lista)

#adicionar elemento no final da lista
lista.append(6)

print("Depois:",lista)

#Remover o último elemento da lista
lista.pop()

print("Removendo:",lista)

#ordenar a lista
lista.sort()

print("Ordenada:",lista)

"""Tupla: é uma estrutura de dados ordenada e *imutável*

"""

tupla = (1,2,3,4,5,3,3,3,3)

indice = tupla.index(1)

print("Posição número 1:",indice)

contagem = tupla.count(3)

print(contagem)

"""**Dicionário**: é uma estrutura de dados que mapeia chaves únicas para valores associados."""

dicionario ={
    'nome' : 'João' ,
    'idade' : '30',
    'cidade' : 'São Paulo'
}

nome = dicionario['nome']

print("Nome:", nome)

dicionario["email"] = 'j@joao.com'

print(dicionario)

"""**Entrada -> Processamento -> Saída**

* Váriaveis (numeros, caracteres, verdadeiro ou falso)
* Operadores lógicos
* Operadores de comparação
* Operadores Matemáticos
* Condicionais
* Loop
* Metódos/Funções

Exemplo 01
"""

tamanho = 8

#Loop para gerar as linhas

for linha in range(tamanho):
  #loop para gerar as colunas
  for coluna in range(tamanho):
    # Se a soma dos indices da linha e da coluna for par, a casa é Y
    if (linha + coluna) % 2 == 0:
      print("X", end=" ")
    else:
      print("Y", end=" ")
  print()

"""**Exemplo 2**"""

matriz_01 = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

matriz_02 = [
    [9,8,7],
    [6,5,4],
    [3,2,1]
]

resultado = [
    [0,0,0],
    [0,0,0],
    [0,0,0]
]

# Loop para as linhas
for i in range(len(matriz_01)): #len = tamanho
  #loop para as colunas
  for j in range(len(matriz_02[0])):
    # loop para multiplicação de elementos
    for k in range(len(matriz_02)):
      resultado[i][j] += matriz_01[i][k] * matriz_02[k][j]
# imprimindo resultado
for linha in resultado:
  print(linha)

import matplotlib.pyplot as plt

# Estrutura base para o exercício
emoji_data = {
    "nome": "Smile",
    "grade": [
        [(255,255,0), (255,255,0), (255,255,0), (255,255,0), (255,255,0)], #
        [(255,255,0), (0,0,0),     (255,255,0), (0,0,0),     (255,255,0)], #
        [(255,255,0), (255,255,0), (255,255,0), (255,255,0), (255,255,0)], #
        [(255,255,0), (0,0,0),     (0,0,0),     (0,0,0),     (255,255,0)], #
        [(255,255,0), (255,255,0), (255,255,0), (255,255,0), (255,255,0)]  #
    ]
}


nova_grade = []

for chave, valor in emoji_data.items():
    if chave == "grade":
        for linha in valor:
            nova_linha = []
            for pixel in linha:

                if pixel == (255, 255, 0):
                    r, g, b = pixel
                    novo_pixel = (r // 2, g // 2, b // 2)
                    nova_linha.append(novo_pixel)
                else:
                    nova_linha.append(pixel)

            nova_grade.append(nova_linha)


emoji_data["grade"] = nova_grade


for linha in emoji_data["grade"]:
    print(linha)

plt.imshow(emoji_data["grade"])
plt.show

biblioteca_musical = {
    "Toques": [
        {"Alegre": ([440, 480], [520, 560])},
        {"Triste": ([200, 150], [100, 50])}
    ]
}


for item in biblioteca_musical["Toques"]:
    for nome, matriz in item.items():

        nova_matriz = []


        linhas = list(matriz)


        for i in range(len(linhas[0])):
            nova_linha = []
            for j in range(len(linhas)):
                nova_linha.append(linhas[j][i])
            nova_matriz.append(nova_linha)


        item.update({nome: nova_matriz})



for item in biblioteca_musical["Toques"]:
    print(item)

import matplotlib.pyplot as plt

playlist = {
    "nome": "Mix Emoji",
    "imagens": [
        {
            "titulo": "Sol",
            "pixels": [
                [(255,255,0), (255,255,0)],
                [(255,255,0), (0,0,0)]
            ]
        },
        {
            "titulo": "Noite",
            "pixels": [
                [(0,0,0), (255,255,0)],
                [(255,255,0), (255,255,0)]
            ]
        }
    ]
}

for chave in playlist.keys():
    if chave == "imagens":

        for imagem in playlist[chave]:

            for linha in imagem["pixels"]:

                for i in range(len(linha)):
                    pixel = linha[i]

                    if pixel == (255,255,0):
                        r, g, b = pixel
                        linha[i] = (r//2, g//2, b//2)


playlist["imagens"].insert(0, {
    "titulo": "Novo",
    "pixels": [[(0,0,0)]]
})


playlist["imagens"].pop()


for img in playlist["imagens"]:
    print(img["titulo"], img["pixels"])

plt.imshow(emoji_data["grade"])
plt.show