# -*- coding: utf-8 -*-
"""sistema_de_auditoria.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vE9C6jfPbNGmW1Kz61EG6M7jFNO5Yg_A

#Sistema de Auditoria de Recursos Corporativos
-> Matheus Montagner
"""

import time

# Auditoria
def auditor(func):
    def Auditoria(*args, **kwargs):
        print("INICIANDO AUDITORIA FINANCEIRA")

        inicio = time.time()
        resultado = func(*args, **kwargs)
        fim = time.time()
        tempo_total = fim - inicio

        return resultado

    return Auditoria

# Estrutura
empresa = {
    "Matriz": {
        "TI": {
            "Infraestrutura": 50000,
            "Desenvolvimento": 80000,
            "Seguranca": 30000
        },
        "RH": {
            "Recrutamento": 20000,
            "Treinamento": 15000
        },
        "Financeiro": {
            "Contabilidade": 25000,
            "Auditoria": 18000
        }
    },
    "Filial": {
        "TI": {
            "Suporte": 22000
        },
        "Marketing": {
            "Publicidade": 40000,
            "Eventos": 12000
        }
    }
}

# Recursão
@auditor
def calcular_orcamento(estrutura, *departamentos_ignorados, **kwargs):
    taxa_cambio = kwargs.get("taxa_cambio", 1)
    moeda_destino = kwargs.get("moeda_destino", "USD")

    def soma_recursiva(no):
        total = 0
        for chave, valor in no.items():
            if chave in departamentos_ignorados:
                print(f"Departamento ignorado: {chave}")
                continue

            if isinstance(valor, dict):
                total += soma_recursiva(valor)

            elif isinstance(valor, (int, float)):
                total += valor

        return total

    total_final = soma_recursiva(estrutura)

    total_convertido = total_final * taxa_cambio

    print(f"\nMoeda destino: {moeda_destino}")
    print(f"Taxa de câmbio aplicada: {taxa_cambio}")

    return total_convertido

resultado = calcular_orcamento(
    empresa,
    "RH",
    "Marketing",
    moeda_destino="BRL",
    taxa_cambio=5.20
)
print(f"\nOrçamento total convertido: R$ {resultado:,.2f}")